language: java

sudo: required

services:
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
    - ~/.m2/repository
    - ~/.ivy2
    - ~/.sbt

before_install:
  - docker version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" --force-yes -y install docker-engine
  - docker version

env:
  - TOGURU_VERSION=$TRAVIS_BUILD_NUMBER

script:
  - docker version
  - docker info
  - ./activator coverage test coverageReport coverageOff docker:publishLocal

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_REPO_SLUG" = "AutoScout24/toguru" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push as24/toguru:$TRAVIS_BUILD_NUMBER;
    fi
  
