sudo: required

services:
  - docker

cache:
  directories:
    - ~/docker

script:
  - echo "$TRAVIS_BRANCH"
  - echo "$TRAVIS_REPO_SLUG"
  - docker version
  - docker info
  - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
  - docker build -t as24/dimmer:$TRAVIS_BUILD_NUMBER .
  - mkdir -p ~/docker; docker save as24/dimmer:$TRAVIS_BUILD_NUMBER > ~/docker/image.tar

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_REPO_SLUG" == "autoscout24/dimmer" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push as24/dimmer:$TRAVIS_BUILD_NUMBER;
    fi
